name: Deploy Documentation
on:
  push:
    branches-ignore:
      - gh-pages
env:
  GIT_COMMITTER_NAME: ci-bot
  GIT_COMMITTER_EMAIL: sjsurobotics@gmail.com
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install the project dependencies
      run: poetry install --no-root
    - name: Build documenation
      run: ./generate.sh
    - run: poetry run mike set-default main
      continue-on-error: true